---

- name: Register UUID of root disk
  become: true
  shell:
    cmd: blkid /dev/vda1 -sUUID -ovalue
  register: UUID

- name: Check UUID is not blank
  fail:
    msg: Couldn't get UUID
  when: UUID.stdout == ""

- name: Edit fstab
  become: true
  mount:
    src: "UUID={{ UUID.stdout }}"
    path: /
    fstype: ext4
    opts: errors=remount-ro,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0
    dump: "0"
    passno: "1"
    state: mounted
  register: fstab

- name: Create default quota user
  become: true
  user:
    name: quotauser
    create_home: no
    system: yes

- name: Ensure new users adopt default quota
  become: true
  lineinfile:
    path: /etc/adduser.conf
    line: QUOTAUSER="quotauser"
    regexp: ^QUOTAUSER=

- name: Initialise quotas
  become: true
  when: ansible_connection != "local"
  shell: "{{ item }}"
  with_items:
    - mount -o remount /
    - quotacheck -cvugm /
    - quotaon -vug /
    - setquota -u quotauser 2G 2G 0 0 /

- name: Enable auto updates/upgrades on boot via cloud-init
  become: true
  when: ansible_connection == "local"
  copy:
    dest: /usr/local/bin/start-quota
    mode: '0755'
    content: |
      #!/bin/bash -e
      if [ "$EUID" -ne 0 ]; then
        echo "ERROR: please run as root"
        exit 1
      fi
      mount -o remount /
      quotaoff /
      quotacheck -cvugm /
      errcode=0
      quotaon -vug / || errcode=1
      if [ "$errcode" != 0 ]; then
        echo 'You may need to reboot the system to load the quota kernel modules ("sudo reboot")'
        exit 1
      fi
      setquota -u quotauser 2G 2G 0 0 /

- name: Tell user how to activate quota on login, if not active
  become: true
  when: ansible_connection == "local"
  copy:
    dest: /etc/profile.d/start-quota.sh
    mode: '0644'
    content: |
      if [ "$(quotaon -p / | grep 'user quota' | grep 'is on')" == "" ] && [ "$(groups | grep jupyterhub-admins)" != "" ]; then
        cat <<-EOF
        Disk quotas are currently off. To turn them on use "sudo start-quota".
        Note: you may need to reboot the system first to enable the quota kernel modules (use "sudo reboot").

      EOF
      fi
