---

- name: Register UUID of root disk
  become: true
  shell:
    cmd: blkid /dev/vda1 -sUUID -ovalue
  register: UUID

- name: Check UUID is not blank
  fail:
    msg: Couldn't get UUID
  when: UUID.stdout == ""

- name: Edit fstab
  become: true
  mount:
    src: "UUID={{ UUID.stdout }}"
    path: /
    fstype: ext4
    opts: errors=remount-ro,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0
    dump: "0"
    passno: "1"
    state: mounted
  register: fstab

- name: Create default quota user
  become: true
  user:
    name: quotauser
    create_home: no
    system: yes

- name: Ensure new users adopt default quota
  become: true
  lineinfile:
    path: /etc/adduser.conf
    line: QUOTAUSER="quotauser"
    regexp: ^QUOTAUSER=

- name: Initialise quotas
  become: true
  when: ansible_connection != "local"
  shell: "{{ item }}"
  with_items:
    - mount -o remount /
    - quotacheck -cvugm /
    - quotaon -vug /
    - setquota -u quotauser 2G 2G 0 0 /

- name: Add start-quota script to /usr/local/bin/
  become: true
  when: ansible_connection == "local"
  copy:
    src: start-quota.sh
    dest: /usr/local/bin/start-quota
    mode: '0755'

- name: Tell user how to activate quota on login, if not active
  become: true
  when: ansible_connection == "local"
  copy:
    src: quota-msg.sh
    dest: /etc/profile.d/quota-msg.sh
    mode: '0644'
