---

- name: Copy plugin
  become: true
  copy:
    src: tljh_custom_plugin
    dest: /opt

- name: Install TLJH
  become: true
  shell: |
    curl -L https://tljh.jupyter.org/bootstrap.py | sudo -E python3 - --plugin /opt/tljh_custom_plugin

- name: Make directory /etc/systemd/system/jupyterhub.service.d
  become: true
  file:
    path: /etc/systemd/system/jupyterhub.service.d
    state: directory

- name: Modify jupyterhub service
  become: true
  copy:
    dest: /etc/systemd/system/jupyterhub.service.d/override.conf
    content: |
      [Service]
      PrivateTmp=no
      PrivateDevices=no
      ProtectKernelTunables=no
      ProtectKernelModules=no
      ExecStartPost=/usr/local/bin/.start-quota-wrapper

- name: Reload jupyterhub service
  become: true
  systemd:
    state: restarted
    name: jupyterhub
    daemon_reload: true

- name: Set config options
  become: true
  shell: "{{ item }}"
  with_items:
    - tljh-config set auth.NativeAuthenticator.check_common_password True
    - tljh-config set auth.NativeAuthenticator.minimum_password_length 6
    - tljh-config set auth.type nativeauthenticator.NativeAuthenticator
    - tljh-config set limits.memory 24G
    - tljh-config set limits.cpu 4
    - tljh-config set services.cull.timeout 3600
    - tljh-config set quota 2G
    - tljh-config set user_environment.default_app jupyterlab
    - tljh-config reload

- name: Create /usr/local/etc/jupyter
  file:
    path: /usr/local/etc/jupyter
    state: directory
  become: true

- name: Set kernel naming scheme in jupyter_config.json
  become: true
  copy:
    dest: /usr/local/etc/jupyter/jupyter_config.json
    content: |
      {
        "CondaKernelSpecManager": {
          "name_format": "conda: {environment}",
          "env_filter": "^/opt/tljh/user$"
        }
      }

- name: Reload config
  become: true
  shell: tljh-config reload hub

- name: Create additional conda environment with latest python
  become: true
  shell: "{{ item }}"
  with_items:
    - /opt/tljh/user/bin/conda install -y nb_conda_kernels
    - tljh-config reload hub
    - /opt/tljh/user/bin/conda create -y -n py3 python=3 numpy scipy matplotlib astropy ipykernel
    - tljh-config reload hub

- name: Create jupyterhub-admins group
  become: true
  group:
    name: jupyterhub-admins
    state: present

- name: Add default user (ubuntu) to "jupyterhub-admins" group
  become: true
  user:
    name: '{{ ansible_user }}'
    groups: jupyterhub-admins
    append: yes

- name: Get nativeauthenticator TEMPLATE_DIR
  become: true
  shell: /opt/tljh/hub/bin/python -c 'from nativeauthenticator.handlers import TEMPLATE_DIR; print(TEMPLATE_DIR)'
  register: TEMPLATE_DIR

- name: Try to patch nativeauthenticator signup page
  become: true
  patch:
    src: "nativeauthenticator-signup.patch"
    dest: "{{ TEMPLATE_DIR.stdout }}/signup.html"
  ignore_errors: true

- name: Reload config
  become: true
  shell: tljh-config reload
