---

- name: Create shared directory
  become: yes
  file:
    path: /srv/data/shared
    state: directory
    group: jupyterhub-admins
    mode: '0775'

- name: Create symlink to shared dir for all new users
  become: yes
  file:
    src: /srv/data/shared
    dest: /etc/skel/shared
    state: link
