---

- name: Remove unattended-upgrades
  become: true
  apt:
    name: unattended-upgrades
    state: absent
    update_cache: yes

- name: Upgrade all packages
  become: true
  apt:
    name: '*'
    state: latest
    update_cache: yes
  register: apt_action
  retries: 100
  delay: 10
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
  # Note: https://saveriomiroddi.github.io/Handling-the-apt-lock-on-ubuntu-server-installations/

- name: Install dependencies
  become: true
  apt:
    name:
      - python3
      - python3-dev
      - git
      - curl
      - snapd
      - quota
      - linux-image-extra-virtual
      - libssl-dev
      - libcurl4-openssl-dev
      - build-essential

- name: Activate quota modules
  become: true
  lineinfile:
    path: /etc/modules
    line: "quota_v{{ item }}"
  with_items:
    - 1
    - 2

- name: Reboot to ensure the quota kernel modules are loaded
  become: true
  when: ansible_connection != "local"
  reboot:

- name: Enable auto updates/upgrades on boot via cloud-init
  become: true
  copy:
    dest: /etc/cloud/cloud.cfg.d/apt-upgrades.cfg
    content: |
      #cloud-config
      package_update: true
      package_upgrade: true
